### ISSUE TITLE
Clarification regarding model prediction on custom data? 

### ISSUE THREAD

**Issue by pavankalyan066** [antonio-mastropaolo/TransferLearning4Code#1]
Hi, I had executed your implementation, and it looks good.

But, could you please explain a little bit about the steps to predict the bugs for the custom dataset?

Thank you.

**Comment by antonio-mastropaolo** [comment]
Hello, I don't think I got your questions.
But before moving on, I would recommend you to read these two paper:
- https://arxiv.org/pdf/1812.08693.pdf
- https://arxiv.org/abs/1812.10772

The first one explains how the authors came up with the bug-fixing dataset. While in the second one, they explain the mutants injection dataset (this one might be closer to your questions)
