### ISSUE TITLE
need help for the pre-trained checkpoint

### ISSUE THREAD

**Issue by eecshope** [antonio-mastropaolo/TransferLearning4Code#2]
Hello! Thanks for your work and contribution. I'm trying to summarize the works of pre-training and I need your help.

I'm trying to reproduce your experiment of fine-tuning but I can't find **the checkpoint of the pre-trained model**. Would you please share it? I tried reproducing the experiment in the previous paper accepted by ICSE 2021 and I found its pre-trained checkpoint. But I can't find the checkpoint of this work. I don't know where to find it.

Thank you so much!

**Comment by antonio-mastropaolo** [comment]
Hello!

Unfortunately, I cannot access the pre-trained checkpoints anymore. Nonetheless, you can easily pre-train the T5 model following the script we provide in this repo using the pre-training dataset available at the following link: https://drive.google.com/file/d/1Mjinf0hWz3Va0AjfkH0hE3l_97JHGuho/view?usp=sharing

I hope this helps you :)

Let me know if you need anything else.
