### ISSUE TITLE
Fully-qualified class names

### ISSUE THREAD

**Issue by jose** [antonio-mastropaolo/TransferLearning4Code#3]
Hi @antonio-mastropaolo,

(Thanks for your quick reply to my other [question](https://github.com/antonio-mastropaolo/T5-learning-ICSE_2021/issues/3).)

In your opinion, to achieve the _best_ prediction, should one provide a focal method with fully-qualified class names, e.g.,

```java
public static org.apache.commons.csv.CSVParser parse(final java.lang.String string, final org.apache.commons.csv.CSVFormat format) throws java.io.IOException {
  org.apache.commons.csv.Assertions.notNull(string, "string");
  org.apache.commons.csv.Assertions.notNull(format, "format");
  return new org.apache.commons.csv.CSVParser(new java.io.StringReader(string), format);
}
```

or a focal method without fully-qualified class names, e.g.,

```java
public static CSVParser parse(final String string, final CSVFormat format) throws IOException {
  Assertions.notNull(string, "string");
  Assertions.notNull(format, "format");
  return new CSVParser(new StringReader(string), format);
}
```

or does not really matter?

--
Best,
Jose

**Comment by antonio-mastropaolo** [comment]
Hello @Jose

Good question!
Honestly, I don't know the extent to which adding fully qualified class names may help the model when generating assert statements. If I were you, I would give both scenarios a try and see differences in performance (if any).

Let me know if you find anything interesting!

**Comment by jose** [comment]
I will give both scenarios a try.  Thank you.
