### ISSUE TITLE
Is the model deterministic?

### ISSUE THREAD

**Issue by jose** [antonio-mastropaolo/TransferLearning4Code#5]
Hi @antonio-mastropaolo,

Just want to confirm with you, is the model deterministic?  I've been using it to generate assert statements and it seems to be.  I've even tried it with different temperature values but got the same output.

--
Best,
Jose

**Comment by antonio-mastropaolo** [comment]
Hi @jose 

In general, if you use the beam decoding mechanism, it is very likely that you always get the same predictions as output.
Instead, if you want to introduce some "randomness" in the decoding mechanism, you can rely on a prediction schema like this one:

```
sample_output = model.generate(
    input_ids, 
    do_sample=True, 
    max_length=50, 
    top_k=0
)
```

Here is an interesting blog post that you might find helpful when generating predictions with different decoding mechanisms.

https://huggingface.co/blog/how-to-generate
